### PR TITLE
Submap images

### PR DESCRIPTION
**Pull request by JakovTomasic**
Designed submap SVG images. Solves #12.

### CODE REVIEW

**Review by Marko132001 — APPROVED** [review]
Looks good to me. You can merge this branch to main.

**Comment by JakovTomasic** [comment]
Thank you. @NikaRodin said she wants to review images, too. She thinks we can improve the colors.

If you want to use the pictures in your branch, you can copy them from here and we'll ignore them in your pull request.

**Review by NikaRodin — CHANGES_REQUESTED** [review]
Great job with the maps! 
As you mentioned, I think we should make some colors a bit brighter. Here are my suggestions: 

main building:
- floor 0:
     - right: f06c3a
- floor 2:
     - left: ffb500
     - right: 1e93d8
- floor 3:
     - left/right: e03353
      
Also, we should do something about the classroom names. Some of them are written in yellow and are difficult to read. Should we make them look better or just leave them for now?

**Comment by JakovTomasic** [comment]
That colors are much better. Thank you. I changed them and changed all big room names to the same color (green, 01ff00)

I think that should be it. I'll request a new review to confirm if the changes are good.

**Review by NikaRodin — APPROVED** [review]
Great work! This looks much better now. You may merge the branch and close the issue.

**Pull request merged**
