### PR TITLE
Functional navigation

### PR DESCRIPTION
**Pull request by JakovTomasic**
Functional search (on the home page) and the navigation page. I conformed all features to work together after merging all of them into a single branch.

Merging this pull request would conclude the [functional navigation](https://github.com/JakovTomasic/RitehMaps/milestone/4) milestone.

### CODE REVIEW

**Review by Marko132001 — APPROVED** [review]
Great job! Everything works as expected. This is a very good demo version.

**Review by NikaRodin — APPROVED** [review]
Everything regarding my parts of the code works well. I approve the changes. 
The app itself works perfectly. You did an amazing job!

**Comment by JakovTomasic** [comment]
The fix for "Required statuses must pass before merging" was to run the action. Actions run only when the .yaml file is in the current branch. I just pulled it from the main branch as explained [here](https://stackoverflow.com/a/2364223).

The command I used: `git checkout origin/main -- .github`

**Comment by lus-terry** [comment]
It's nice to see all the pieces come together. The app works great!

**Review by lus-terry — APPROVED** [review]
It's nice to see all the pieces come together. The app works great!

**Pull request merged**
